# Generated by Django 5.2 on 2025-04-10 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_syllabusrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(help_text="We'll contact you via this email", max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Optional contact number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('course', models.CharField(help_text="Select the course category you're interested in", max_length=255, verbose_name='Course Interest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('is_processed', models.BooleanField(default=False, help_text='Mark as processed when addressed', verbose_name='Processed Status')),
            ],
            options={
                'verbose_name': 'Query Request',
                'verbose_name_plural': 'Query Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='api_queryre_email_83b824_idx'), models.Index(fields=['created_at'], name='api_queryre_created_9f84be_idx'), models.Index(fields=['is_processed'], name='api_queryre_is_proc_aa024d_idx')],
            },
        ),
    ]
