# Generated by Django 5.2 on 2025-04-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_queryrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='queryrequest',
            name='api_queryre_email_83b824_idx',
        ),
        migrations.RemoveIndex(
            model_name='queryrequest',
            name='api_queryre_created_9f84be_idx',
        ),
        migrations.RemoveIndex(
            model_name='queryrequest',
            name='api_queryre_is_proc_aa024d_idx',
        ),
    ]
