# Generated by Django 5.2 on 2025-04-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_queryrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('price', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
            ],
        ),
    ]
