# Generated by Django 5.2 on 2025-04-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Technology', 'Technology'), ('Business', 'Business'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Personal Development', 'Personal Development')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('All Levels', 'All Levels'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Regular', 'Regular')], max_length=20),
        ),
    ]
