# Generated by Django 5.2 on 2025-04-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_syllabus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Syllabus',
            new_name='Syllabi',
        ),
    ]
