# Generated by Django 5.2 on 2025-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_syllabus_syllabi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabi',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
