# Generated by Django 5.2 on 2025-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_syllabi_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabi',
            name='startDate',
            field=models.DateField(),
        ),
    ]
