# Generated by Django 5.2 on 2025-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_syllabi_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabi',
            name='startDate',
            field=models.CharField(max_length=50),
        ),
    ]
