# Generated by Django 6.0.3 on 2026-03-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_syllabi_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabi',
            name='course',
        ),
        migrations.DeleteModel(
            name='SyllabusRequest',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Syllabi',
        ),
    ]
