# Generated by Django 6.0.3 on 2026-03-30 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_syllabi_course_delete_syllabusrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Optional contact number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
