# Generated by Django 6.0.3 on 2026-03-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_subscriber_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryRequest',
        ),
    ]
