# Generated by Django 6.0.3 on 2026-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_paymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_address', models.TextField()),
                ('company_gstin', models.CharField(max_length=15)),
                ('country_applying_for', models.CharField(max_length=100)),
                ('company_website', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='submissions/pdfs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
