# Generated by Django 6.0.3 on 2026-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_companyapplication_documentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapplication',
            name='company_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
