# Generated by Django 6.0.7 on 2026-07-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_companyapplication_company_gstin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyApplication',
        ),
        migrations.DeleteModel(
            name='DocumentSubmission',
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
